### ISSUE TITLE
Feature: Allow webpack extensions.

### ISSUE THREAD

**Issue by jspears** [electrodejs/electrode-archetype-react-app#19]
Should work the same as https://github.com/electrode-io/electrode-archetype-react-component/issues/12 ,

**Comment by dan3721** [comment]
What is the ETA for this feature?

**Comment by jchip** [comment]
electrode repos have been consolidated at https://github.com/electrode-io/electrode.  webpack extensions is implemented.

**Comment by dan3721** [comment]
I'm sorry what does "repos have been consolidated" mean. Is Sass now supported / is there some doc somewhere?

[Is this the magic?](https://github.com/electrode-io/electrode/blob/master/packages/electrode-archetype-react-app-dev/config/webpack/partial/extract-style.js):

`  
if (cssModuleSupport) {
    rules.push({
      _name: "postcss",
      test: /\.scss$/,
      use: [
        {
          loader: "postcss-loader",
          options: {
            browsers: ["last 2 versions", "ie >= 9", "> 5%"]
          }
        }
      ]
    });
  }
`

**Comment by nischaym** [comment]
@jchip can you answer @dan3721's question ?

**Comment by VinitSarvade** [comment]
Any info here?
