### ISSUE TITLE
Images in ./dist/js

### ISSUE THREAD

**Issue by Eric013** [electrodejs/electrode-archetype-react-app#27]
Hello,

Thanks for your work and sharing.
After **gulp build**, I don't understand why generate images in ./dist/js instead of ./dist/images ?

**Comment by jchip** [comment]
This really has more to do with naming that dir `js`.  It'd be nice to configure webpack so the emit files go to certain directories according to their extensions.

**Comment by rbudiharso** [comment]
+1
