### ISSUE TITLE
Move babel configuration to `babel-preset-electrode-react`

### ISSUE THREAD

**Issue by wmertens** [electrodejs/electrode-archetype-react-app#32]
That way it's easier to configure `.babelrc` in projects, `presets: ["electrode-react"]` instead of depending on the full path to the file in this module.

**Comment by codiemullins** [comment]
I took a stab at this:

* github: [https://github.com/codiemullins/babel-preset-electrode-react](https://github.com/codiemullins/babel-preset-electrode-react)
* npm: [https://www.npmjs.com/package/babel-preset-electrode-react](https://www.npmjs.com/package/babel-preset-electrode-react)

I verified it by following the Getting Started guide but replacing the `.babelrc` file with the JSON below. The code for the app is available [here](https://github.com/codiemullins/babel-preset-electrode-react).

```
{
  "presets": ["electrode-react"]
}
```

I wasn't sure of the contribution process with electrode but wanted to give this a shot and give back. If there's anything else I can provide to assist on this issue please let me know. Thank you all for the great work!

**Comment by ananavati** [comment]
thanks much @codiemullins for quickly jumping and coming up with a solve.
thanks @wmertens for suggesting this `enhancement`, makes the `project/.babelrc` file much more cleaner.

we will make sure to add `babel-preset-electrode-react` in electrode repos.

**Comment by jchip** [comment]
@codiemullins could you give me owner permission to the module please?  would you mind PR the repo into the new lerna repo as a packages as well please?  https://github.com/electrode-io/electrode/tree/master/packages

**Comment by jchip** [comment]
issue's been moved to the new repo https://github.com/electrode-io/electrode/issues/564
