### ISSUE TITLE
.eslintrc and eslint version issues

### ISSUE THREAD

**Issue by mypark** [electrodejs/electrode-archetype-react-app#64]
Not sure what the right way of doing this is.  My issue is that I have an .eslintrc file in the root of my project with some rules,

```
{
    "parser": "babel-eslint",
    "ecmaFeatures": {
      "jsx": true
    },
    "env": {
        "es6": true,
        "browser": true
    },
    "plugins": [ "filenames" ],
    "extends": "walmart/configurations/es6-react-test",
    "rules": {
        "indent": [2, 2],
        "quotes": [2, "single"],
        "object-curly-spacing": [2, "always"],
        "comma-dangle": [2, "always-multiline"]
    }
}
```

 and when I run `gulp check` and I get an error 

```
Error: walmart/rules/eslint/best-practices/on:
	Configuration for rule "no-labels" is invalid:
	Value "2,[object Object]" has more items than allowed.
```

I'm thinking this is because I'm using a different eslint version then the archetype, which seems to be version 1.10.3 wheras I'm using 2.10.2 which is what eslint-config-walmart tracks against.  I'm a bit of a beginner in configuring eslint so let me know if I'm missing something very basic here.

It would be nice to continue to use the gulp check task so I'm wondering what I can do to make my eslint play nicely with the archetype.

**Comment by citelao** [comment]
There's a pull request pending to allow overrides locally (https://github.com/electrodejs/electrode-archetype-react-app/pull/35).

I think they're still waiting on a response from the original pull-requester.

**Comment by citelao** [comment]
This project is deprecated, but the most recent version has a pull request that might fix it (https://github.com/electrode-io/electrode/pull/75). #35 on *this* project that had similar suggestions.

**Comment by citelao** [comment]
Addendum: `gulp check` actually respects existing .eslint files—provided they are in the correct directories:

- `client/`
- `server/`
- `test/client/`
- `test/server/`

I do not believe it works globally. Just import a global one into several smaller `.eslintrc`s if necessary.
