### ISSUE TITLE
Slowness every time triggering a link 

### ISSUE THREAD

**Issue by bubuzzz** [electrodejs/electrode-archetype-react-app#65]
We are developing a quite complicated project and everytime I click on a link during the development (`gulp dev`), I have to wait a lot of time for the bundle files downloaded back to the client 

![developer_tools_-_http___222_clearbridgegroup_com_au_4000_admin_home_and_clearbridge_admin_management](https://cloud.githubusercontent.com/assets/571736/21163093/1da00ce2-c1e5-11e6-91f7-830a0453bbf5.png)
 

This happens nearly all the times and reduces the productivity a lot. Is there any way to improve this situation ?

**Comment by ananavati** [comment]
@bubuzzz 

> This happens nearly all the times and reduces the productivity a lot. Is there any way to improve this situation ?

Electrode by itself only calls webpack to compile your bundle, so your time to re-load the bundle depends on how long webpack takes to compile and restart webpack-dev-server

from the screenshot I see that the bundle size is 10.7MB Whoa! Can you please mention the time it takes for webpack to compile your bundle every-time you make the change? thats a huge bundle and sending a  bundle that big over a network will be obviously slow.

**Comment by bubuzzz** [comment]
@ananavati The compilation time of webpack is actually quite fast, only around 2 or 3 seconds most of the time. I observed it from the moment of bundling till the moment the server resfreshed

```
webpack bundle is now INVALID
webpack bundle is now VALID
webpack report is served from http://localhost:2992/reporter
[nodemon] restarting due to changes...
[nodemon] starting `node server/index.js`

```

**Comment by bubuzzz** [comment]
One way to optimize the client is trying to load the necessary import but it does not improve that much. Is there any other way to optimize the client side? Is there anything i could do with the web pack configuration in order to get over the issue ? Also, how can I configure the webpack in electrode ?

**Comment by ananavati** [comment]
importing only what is needed will help, along with that we will be releasing these features as part of the pr https://github.com/electrode-io/electrode/pull/75

* Webpack DLL support which will let you split the bundle into multiple chunks.
* Webpack config override support from root project.

**Comment by bubuzzz** [comment]
Thank @ananavati . I think I am clear for now. Feel free to close the ticket
